version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
artifacts:
  - path: MossApp\bin\Debug\MossApp.exe
    name: MossApp
deploy:
  release: MossApp-$(appveyor_repo_tag_name)
  description: 'MossApp $(appveyor_repo_tag_name) has been released.'
  provider: GitHub
  auth_token:
    secure: s1IEmaaYPxsqkxivyhxf/ysmYQGg+JL3iBqzjeHwa06txM7is/kG5yR8iVZUvkiZ
  artifact: MossApp
  draft: false
  prerelease: false
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
