version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
deploy:
  release: MossApp-v$(appveyor_build_version)
  description: 'GUI for Moss'
  provider: GitHub
  auth_token:
    secure: s1IEmaaYPxsqkxivyhxf/ysmYQGg+JL3iBqzjeHwa06txM7is/kG5yR8iVZUvkiZ
  artifact: /.*\.exe/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
